version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/authdb
      - JWT_SECRET=supersecretjwtkey
    depends_on:
      - postgres

volumes:
  postgres-data:
